### ISSUE TITLE
Missing ISO codes for countries

### ISSUE THREAD

**Issue by xantari** [KevMorelli/Country-Region-City-MSSQL#1]
Would be great to have the ISO codes included.

**Comment by KevMorelli** [comment]
The ISO codes are included in the Code column

Check the script
https://github.com/KevMorelli/Country-Region-City-MSSQL/blob/master/Scripts/02%20-%20Insert%20Countries.sql

**Comment by zelalemtekabe** [comment]
There are 502 region names missing in the Regions Table, is it possible to get this updated?

**Comment by KevMorelli** [comment]
@zelalemtekabe that has to be done manually by someone who knows which regions are, like the readme file says, this is just an adaptation of another repository but that one hasn't been updated in a while
